### ISSUE TITLE
Terminal cleanup?

### ISSUE THREAD

**Issue by mashephe** [JeffersonLab/HDGeant4#102]
Hi,

Feel free to close this if you don't think it is an "issue" but it would be nice to suppress some of the output from hdgeant4.  I find when I start hdgeant4 it prints tons of what looks like material definition, particle definition, etc.  It renders the terminal completely useless and likely dilutes any error message that may appear.  Is there a way to turn off a lot of this output that doesn't seem relevant to the average user?

Matt

**Comment by nsjarvis** [comment]
I was also going to put in a request to suppress this.  I find that the
particle & material definitions are followed by an awful lot of GeomNav0003
G4Exception warning messages.
Running hdgeant4 to send output into a file, 2.5M events generates a 64MB
text file.   I've also seen many many pages of warnings of 100+ hits in the
FDC (in the same event!) being ignored but cannot find an exact example
right now.

Naomi.

**Comment by rjones30** [comment]
Hello Matt,

I propose the following change to address this issue.

   - add a new -d <debug_level> switch on the commandline which enables
   various levels of debug information. The default will be only to print G4
   output messages when there is a fatal error, equivalent to debug_level 0.
   Setting debug_level to 1 will print warning messages about dropped hits in
   the FDC, etc. like Noami described, but not the extended startup messages.
   Setting debug_level >1 will give the present behavior, which is to print
   out all of the messages you presently see.
   - none of this will block the usual G4 startup and JANA messages about
   reading calibration constants, as hdgeant and hd_root and mcsmear do this
   and there has not been any move to suppress that.

Comments welcome.

-Richard Jones

**Comment by nsjarvis** [comment]
Sounds great.

**Comment by mashephe** [comment]
Agree that this sounds like a good solution -- anything that leaves me with a usable terminal window is fine.

Matt

**Comment by nsjarvis** [comment]
I would like to request occasional output of the # events completed as indication of progress, please. 
A marker every 10% of the total events would be enough without being annoying.
Should I submit this as a separate feature request?

**Comment by markito3** [comment]
It is much cleaner now.
