### ISSUE TITLE
Skip (in control.in) is ignored

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#103]
I think the instruction skip in control.in is not used.
If this is intentional it should be documented.

I ran geant twice on the same input file, once with skip=0 and another time with skip=1000.
Hdview2 shows that first event in each output file are both event #1 and contain the same info.  The subsequent events are ordered differently so I didn't look for further examples as anyway I thought the second file should start at event 1000.

I realise that this is an unusual application.  My large input file was taking too long to process so (not knowing how to split up the input file although I'm sure this can be done) I duplicated the file and then asked several jobs to process different sections of it.  Then I thought I had better check that were doing what I thought they were.

This is not a feature request; if skip really is ignored then just documenting that is ok with me.

![hddm_vis](https://user-images.githubusercontent.com/15655254/56438388-cc212080-62b0-11e9-9177-a5928bd70f12.png)

**Comment by rjones30** [comment]
Hello Naomi,

Thank you for this alert, the SKIP card is handled as expected in hdgeant,
but for some reason I never implemented it in hdgeant4. I will package
hdgeant4 support for SKIP together with the update to change the default
behavior of hdgeant4 without commandline arguments.

-Richard Jones

**Comment by sdobbs** [comment]
Fixed by #112, closing.
