### ISSUE TITLE
Run number read in from two places is confusing

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#104]
HDGeant4 reads the run number from control.in as RUNG and again from the command line -r parameter.  The command line param supersedes control.in 

I don't see the value of setting it in the command line, given that we cannot set the output filename in the command line.   Being able to set both of these in the command line would be more useful.   Being able to set it in two different places can be a source of confusion.

In any case it should be documented that the command line setting overrides the input file value.

**Comment by rjones30** [comment]
Hello Naomi and all,

Here is how the run number in the output to hdgeant4 is assigned, in order
of precedence from low to high. Higher precedence assignment replaces lower
if both are present.

   1. the number number stored in the input hddm file, set by the
   generator, in case of external generator
   2. the RUNG card in control.in (standard card from G3 library, carried
   over to hdgeant4 for consistency)
   3. the RUNNO card in control.in (another spelling for RUNG, carried over
   from hdgeant)
   4. the -r commandline argument

Comments are welcome.

-Richard Jones

**Comment by nsjarvis** [comment]
This can be fixed by copying the documentation above into control.in

**Comment by rjones30** [comment]
Hello Naomi,

Can you execute the pull requests that I just posted to the
JeffersonLab/hdgeant4 and JeffersonLab/halld_sim repositories on github?
Those are to complete this work we discussed on the run number, and fix
inconsistencies in the way this was being handled in hdgeant and hdgeant4.
For example, hdgeant did not used to support the commandline option. Now it
does, just like hdgeant4.

-Richard

**Comment by nsjarvis** [comment]
Hi Richard,

I started running through the 4 ways to set the run number, starting with
hdgeant, pulled from this branch in halld_sim.

hdgeant -r 12345   causes some initial complaints from JANA - unable to
open event source and no valid event sources given - but it continues to
run, shows the correct run number requested from ccdb and sets the run
number correctly in the output file.

RUNNO looks like it works, but actually it isn't reaching the output file.
I changed the line in control.in from RUNG 51500 to RUNNO 30000.  When
hdgeant ran, it printed the correct run number 30000 to the screen, but the
output file contains the run number which is embedded in my bggen INFILE.

While you're looking at this, would it be worth adding a line to remind
people only to use valid run numbers, ie 10000 and greater, to avoid people
reporting problems from nonexistent runs?   It seems that there are several
different ways of handing problem run numbers.  If the run number in the
command line is too small (eg 1000), hdgeant then tries to use RUNG in
control.in. If RUNG is not present then it uses the run number in the
INFILE.  However if RUNG is present but also too small, hdgeant crashes.
Originally I typed 1000 by accident and spotted this as soon as I saw the
JANA error, but the ensuing behaviour was odd enough that I tried to work
out what was going on.

Best,
Naomi.

**Comment by rjones30** [comment]
Naomi,

RUNNO looks like it works, but actually it isn't reaching the output file.


Right, good catch. I have submitted an update to my pull request that
corrects this faulty behavior in hdgeant.

 While you're looking at this, would it be worth adding a line to remind
> people only to use valid run numbers, ie 10000 and greater, to avoid people
> reporting problems from nonexistent runs?


This is more a ccdb issue, more likely that the user has selected the wrong
ccdb sqlite file than that they are using
the wrong run number. In general, there should be a default value in every
table that is taken if the run number does not
fall in one of the ranges for which special calibrations have been run. Of
course the user may select some variation for
which the tables are extremely sparse. In that case, it is probably not the
run number that is wrong, but the ccdb he is
using is not the correct one. If this happens for any subdetector, are you
suggesting that the simulation should exit
with a warning that the user is trying to run on a ccdb that is not
correctly configured for the desired run number?

-Richard Jones

**Comment by nsjarvis** [comment]
I agree it's a ccdb/user issue.  Although it would be nice if hdgeant didn't actually crash after asking ccdb for a nonexistent run number, it probably isn't worth putting time into fixing that particular thing.

**Comment by rjones30** [comment]
Hello Naomi,

The reason I haven't done anything about this so far is that, in the way I
do MC, there is no such thing as a non-existent run, just real runs and
virtual runs. I have often organized my work by grouping runs in the range
5000-9999 under different test configurations to see what the performance
of the detector and/or beamline would be under these various conditions. I
would not want the sim to bomb out as soon as I give it a run number 9001,
since that was the run I used for a major osg production some months back.
Likewise people working on future proposals can create special run periods
for their test configs. It is not great to re-use real run numbers and
implement the exceptional conditions as a variation in ccdb because then
there is always the question of which set of constants actually were used.
Having a virtual run number guarantees that you are getting special values
from ccdb corresponding to your test setup -- or it won't even run.

-Richard J.
