### ISSUE TITLE
Reading in # events and source

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#105]
I realise that the HDGeant4 input macro file can ask it to do many other things than run the events and exit, but for most applications we do just need it to run n events taking the parameters from control.in and maybe reading another input file.  Would it be possible to have it read the number of events from TRIG in control.in (and run and exit by itself) if a macro file is not supplied?  

Putting /run/BeamOn into my HDGeant4 macro is worrying when I am supplying an input file and don't want to use the BEAM card.  It looks like I am asking for both.  Would it be possible to change the keyword to something that doesn't mention beam, like events, or run?

**Comment by rjones30** [comment]
Hello Naomi and all,

The use of the word "beam" in /run/BeamOn has nothing to do with the same
word that appears in the BEAM line in control.in; the command /run/BeamOn
simply starts simulating events from whatever source you are requesting in
control.in, whereas the card BEAM in control.in defines GlueX photon beam
parameters.

To help mitigate this possible confusion, and also make the commandline
experience of running hdgeant and hdgeant4 more similar, I propose the
following change. Note that this deviates from the recommended G4 main
program behavior as illustrated in the G4 examples directory. Whatever,
that doesn't matter, let's do what makes sense for us. Right now, if you do
"hdgeant4" without arguments, you get interactive mode with a command
prompt, to which you respond "/run/beamOn 1000" to generate 1000 events
from whatever event source. This proposal changes that to:

   1. If you run "hdgeant4" without arguments, it will behave just like
   hdgeant, and automatically generate TRIG (from control.in) events, then
   exit.
   2. If you want the interactive prompt, do "hdgeant4 -i" and it will
   behave just like "hdgeant4" did before.
   3. If you have existing scripts that set up a run.mac file and then do
   "hdgeant4 run.mac", those will behave just like before, no change.

Comments welcome.

-Richard Jones

**Comment by nsjarvis** [comment]
Hi,

That sounds great.  I'm sure there will be feedback from others in the next
software (G4) meeting.

Best,
Naomi.

**Comment by faustus123** [comment]
FWIW: I like this too. Using “-i” to get an interactive session is very consistent with
ccdb and I believe other packages.


Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist, Thomas Jefferson National Accelerator Facility
Newport News, VA
davidl@jlab.org<mailto:davidl@jlab.org>
(757) 269-5567 W
(757) 746-6697 C


On Apr 20, 2019, at 9:32 AM, Richard Jones <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello Naomi and all,

The use of the word "beam" in /run/BeamOn has nothing to do with the same
word that appears in the BEAM line in control.in; the command /run/BeamOn
simply starts simulating events from whatever source you are requesting in
control.in, whereas the card BEAM in control.in defines GlueX photon beam
parameters.

To help mitigate this possible confusion, and also make the commandline
experience of running hdgeant and hdgeant4 more similar, I propose the
following change. Note that this deviates from the recommended G4 main
program behavior as illustrated in the G4 examples directory. Whatever,
that doesn't matter, let's do what makes sense for us. Right now, if you do
"hdgeant4" without arguments, you get interactive mode with a command
prompt, to which you respond "/run/beamOn 1000" to generate 1000 events
from whatever event source. This proposal changes that to:

1. If you run "hdgeant4" without arguments, it will behave just like
hdgeant, and automatically generate TRIG (from control.in) events, then
exit.
2. If you want the interactive prompt, do "hdgeant4 -i" and it will
behave just like "hdgeant4" did before.
3. If you have existing scripts that set up a run.mac file and then do
"hdgeant4 run.mac", those will behave just like before, no change.

Comments welcome.

-Richard Jones

**Comment by rjones30** [comment]
This has now been implemented! Please check and then close this issue.
-Richard J.

**Comment by nsjarvis** [comment]
Done!  Checked all 3.  Thank you.
