### ISSUE TITLE
Feature request - progress indicator

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#107]
I would like to request occasional output of the # events completed as indication of progress, please.

**Comment by rjones30** [comment]
You already have this capability with the DEBUG line in control.in
DEBUG count1 count2
The meaning of the fields are as follows:
- print a message at the beginning of every event, up to count1
- after event count1, print a message at the beginning of each block of count2 events

For example, DEBUG 10 1000 will print a message at the start of the first 10 events, and after that event 1001, 2001, 3001, etc. This is similar to how it works in hdgeant. Is this sufficient?

-Richard Jones

**Comment by nsjarvis** [comment]
Yes, the functionality is fine, but the text in control.in contradicts what you wrote above.  

> c The following card sets up the simulation to perform debugging on
c a subset of the simulated events.
c DEBUG first last step
c  - first (int) = event number of first event to debug
c  - last (int) = event number of last event to debug
c  - step (int) = only debug one event every step events
DEBU 1 10 2

I anticipated that DEBUG would do more than print the event number.  I think there are other debug options elsewhere (compile-time) but it would be good to say that by default the debug info is just 
G4WT0 > >>> Event 1
G4WT0 > >>> Event 2 
etc.

After reading control.in, I expected the line DEBU 1 10 2 to request the debug info for events 1,3,5,7,9 only, ie debug from first to last, every step, like a regular software loop.  Instead, the event numbers were printed for 1,2,3,4,5,6,7,8,9,11,13,15,17,19 etc. as you described.

Please could you change control.in to make this more clear?

**Comment by rjones30** [comment]
Naomi, I went into control.in to try to do this, and but as soon as I got started I realized that the DEBUg card in geant3 has a big history and a lot of poorly documented features that are difficult to explain in just a few lines. And none of that elaborate debug printout behavior directed by the flags on the SWIT card has been replicated in hdgeant4. I decided to drop DEBUg card support from hdgeant4, and go with a much more simple power-of-ten progress printout. Please have a look at two pull requests that I have submitted for this.

1. halld_sim - changes to control.in to better document how DEBU works
2. HDGeant4 - same updates to control.in, plus new code to implement the simplified progress printout lines.

**Comment by rjones30** [comment]
Naomi,

Have you seen my action on this?

-Richard

**Comment by nsjarvis** [comment]
Oh my, I thought this would be an easy fix.  (Sorry, I was ignoring emails this afternoon).

**Comment by nsjarvis** [comment]
It looks like this is all sorted.  Thank you!
