### ISSUE TITLE
G4Exception crash after Curve length mis-match

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#109]
I have seen this a few times with different jobs, the smallest had 250,000 events. 
The error message is pasted below and the terminal output file is attached.
Control.in is also attached.  The input file (created by gen_amp) was 1.1GB, not too unwieldy to share.

(My job # was 468991)

G4WT15 > 
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomNav0003
      issued by : G4PropagatorInField::ComputeStep()
Curve length mis-match between original state and proposed endpoint of propagation.
  The curve length of the endpoint should be: 1925.17
  and it is instead: 1934.89.
  A difference of: -9.72025
  Original state =  (  X= -8.2995965 3.26379871 749.508334  P= -0.0599843239 0.0185442487 2.5652412e-05  Pmag= 0.0627854198 Ekin= 0.00384271123 l= 0 m0= 0.510999 (Pdir-1)= 0 t_lab= 4.34676 t_proper= 0 PolV= (0,0,0)  ) 
  Proposed state =  (  X= -8.26161648 3.24548047 752.759854  P= -0.0514308565 0.0360086236 0.000525174561  Pmag= 0.0627855858 Ekin= 0.00384273148 l= 1934.89198182 m0= 0.510999 (Pdir-1)= 0 t_lab= 0 t_proper= 0 PolV= (0,0,0)  ) 
*** Fatal Exception *** core dump ***
-------- EEEE -------- G4Exception-END --------- EEEE -------

G4WT15 > 
G4WT15 > *** G4Exception: Aborting execution ***
Abort
 

[4pi_t05_g4_40946_250000_control.in.txt](https://github.com/JeffersonLab/HDGeant4/files/3121860/4pi_t05_g4_40946_250000_control.in.txt)

[g4_40946_0_250000.o468991.txt](https://github.com/JeffersonLab/HDGeant4/files/3121823/g4_40946_0_250000.o468991.txt)

**Comment by rjones30** [comment]
Hello Naomi,

This is a completely different symptom than the event you showed before.
Here there is a failure of the magnetic field integrator to get a
consistent answer compared to a simple helical estimator. This generally
happens where the field is very strong (reported in the mailing lists for B
> 5T). But here in your error output it says the problem occurs on the beam
axis inside the target with a low-energy electron (4 MeV). Has anyone else
seen this one?

-Richard Jones

**Comment by nsjarvis** [comment]
I have a few more of these.  Is the info that I pasted into the message enough for each one, or do you need the attached files too?   I'll try to extract a crashing event for you to play with.

**Comment by rjones30** [comment]
Naomi,

If you could get it to happen in a single-threaded run, then there is a
chance of making it reproducible. Alternately, if you could have it print
out the initial seeds at the start of each event, that print would be
tagged by the thread id and we could find the start of the deadly event
that way. To print out the initial seeds, you need to add a line to enable
the compile-time switch VERBOSE_RANDOMS in GNUmakefile in the HDGeant4
build directory and then do "make". Of course, in that case there will be a
big bloat in the output log as every event will produce a printout of its
seeds.

-Richard Jones

**Comment by nsjarvis** [comment]
I have a new one of these.   Will try it again single-threaded later on

G4WT13 > 
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomNav0003
      issued by : G4PropagatorInField::ComputeStep()
Curve length mis-match between original state and proposed endpoint of propagation.
  The curve length of the endpoint should be: 1468.29
  and it is instead: 1469.09.
  A difference of: -0.793889
  Original state =  (  X= -8.36097977 -2.14028764 725.928495  P= -0.0634571555 0.00460788845 1.47044673e-05  Pmag= 0.0636242362 Ekin= 0.00394567873 l= 0 m0= 0.510999 (Pdir-1)= -2.22045e-16 t_lab= 8.28535 t_proper= 0 PolV= (0,0,0)  ) 
  Proposed state =  (  X= -8.42681028 -2.3782649 731.321488  P= 0.0556631306 -0.0308136251 0.000466318728  Pmag= 0.0636245318 Ekin= 0.00394571525 l= 1469.08548398 m0= 0.510999 (Pdir-1)= 0 t_lab= 0 t_proper= 0 PolV= (0,0,0)  ) 
*** Fatal Exception *** core dump ***
-------- EEEE -------- G4Exception-END --------- EEEE -------

G4WT13 > 
G4WT13 > *** G4Exception: Aborting execution ***
Abort


[g4_40946_bggen_5000003_control.in.txt](https://github.com/JeffersonLab/HDGeant4/files/3186461/g4_40946_bggen_5000003_control.in.txt)

[g4_40946_bggen_5000003.out.txt](https://github.com/JeffersonLab/HDGeant4/files/3186462/g4_40946_bggen_5000003.out.txt)

[g4_40946_0_5000003.o470996.txt](https://github.com/JeffersonLab/HDGeant4/files/3186463/g4_40946_0_5000003.o470996.txt)

**Comment by nsjarvis** [comment]
I hope I have managed to trap one of these rogue events at last.   I have attached it (in a hddm file with txt extension added).

The starting seeds are below.

G4WT8 > New event 1219154 with starting seeds 1512673414, 186493231


[bggen_5000011_event_1219154.hddm.txt](https://github.com/JeffersonLab/HDGeant4/files/3347314/bggen_5000011_event_1219154.hddm.txt)

**Comment by rjones30** [comment]
Hello Naomi,

I am getting notified each time you post to the HDGeant4 github issues, no
need to send me a follow-up notification. I will look and see if I can
reproduce it.

-Richard

**Comment by rjones30** [comment]
I suggest that this issue be looked at again, following implementation of the fixes that were introduced in response to issue #143.

**Comment by nsjarvis** [comment]
Unfortunately I still see this happening.    I have one example which crashed in the first 1000 events.  
The output should say New event <event-number> with starting seeds... at present it does not supply the event number.
I'll request that in a separate issue.

Please could you remind me how to strip the first 1000 evts out of the hddm file to share with you?

**Comment by nsjarvis** [comment]
There's a lot more info from the crash than previously.   The one below is from my file g4-10-4_rpt_40946_5000011.in.e190420

I have two new examples of this type of crash, and another 7 jobs still running.  
I used combos of bggen file, run number and random seed which I had found to crash at some point previously (not every time) with g4-10-2 so although it's annoying that the bug is still present, if it's more repeatable then that's an improvement. 

Using Geant4 version Name: geant4-10-04-patch-02 [MT]   (25-May-2018)  with 16 threads


G4WT5 > 
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomNav0003
      issued by : G4PropagatorInField::ComputeStep()
Curve length mis-match between original state and proposed endpoint of propagation.
  The curve length of the endpoint should be: 28.9926
  and it is instead: 29.1195.
  A difference of: -0.126834
  Original state =  (  X= -8.67334718 6.62656763 2706.18117  P= -0.0223917307 0.0743730801 0.241737979  Pmag= 0.253909423 Ekin= 0.0596059279 l= 
0 m0= 0.510999 (Pdir-1)= 0 t_lab= 8.99209 t_proper= 0 PolV= (0,0,0)  ) 
  Proposed state =  (  X= -8.87632134 6.68046342 2733.90399  P= -0.0568713897 -0.052918961 0.241733787  Pmag= 0.253909423 Ekin= 0.0596059279 l= 
29.1194696511 m0= 0.510999 (Pdir-1)= 0 t_lab= 0 t_proper= 0 PolV= (0,0,0)  ) 
*** Fatal Exception *** core dump ***
G4WT5 > G4Track (0x7fbe113134f0) - track ID = 268, parent ID = 227
G4WT5 >  Particle type : e- - creator process : eIoni, creator model : Undefined
G4WT5 >  Kinetic energy : 59.6059 keV - Momentum direction : (-0.0881879,0.292912,0.952064)
G4WT5 >  Step length : 0 fm  - total energy deposit : 0 eV 
G4WT5 >  Pre-step point : (-8.67335,6.62657,2706.18) - Physical volume : LASS::1 (Air)
G4WT5 >  - defined by : not available
G4WT5 >  Post-step point : (-8.67335,6.62657,2706.18) - Physical volume : LASS::1 (Air)
G4WT5 >  - defined by : eIoni - step status : 7
G4WT5 >  *** Note: Step information might not be properly updated.
G4WT5 > 
-------- EEEE -------- G4Exception-END --------- EEEE -------

G4WT5 > 
G4WT5 > *** G4Exception: Aborting execution ***
Abort

**Comment by rjones30** [comment]
I have been able to reproduce this problem. I am working on it now, and will post a diagnosis and fix shortly. -Richard

**Comment by nsjarvis** [comment]
Fantastic!  Lmk if you need anything more from me.

Naomi.

**Comment by rjones30** [comment]
Naomi, I have submitted a PR for this problem. It involves another patch to one of the core G4 library classes that I already patched for another related, but different problem. Please execute the PR and test it.
-Richard Jones

**Comment by nsjarvis** [comment]
Will do.

**Comment by nsjarvis** [comment]
All looks good, thank you.
