### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#110]
The stack trace is in the attached file g4_40946_0_5000003.o470940.txt

[g4_40946_bggen_5000003.out.txt](https://github.com/JeffersonLab/HDGeant4/files/3179365/g4_40946_bggen_5000003.out.txt)
[g4_40946_0_5000003.o470940.txt](https://github.com/JeffersonLab/HDGeant4/files/3179366/g4_40946_0_5000003.o470940.txt)

[g4_40946_bggen_5000003_control.in.txt](https://github.com/JeffersonLab/HDGeant4/files/3179357/g4_40946_bggen_5000003_control.in.txt)
[hdg4.in.txt](https://github.com/JeffersonLab/HDGeant4/files/3179358/hdg4.in.txt)

**Comment by sdobbs** [comment]
This is the thread that crashed:

Thread 24 (Thread 0x2adfcd000700 (LWP 3914)):
#0  0x00000038580ac86d in waitpid () from /lib64/libc.so.6
#1  0x000000385803e479 in do_system () from /lib64/libc.so.6
#2  0x000000385803e7b0 in system () from /lib64/libc.so.6
#3  0x00002adf5b7c955a in TUnixSystem::StackTrace() () at /home/gluex/root/root-6.06.08/core/unix/src/TUnixSystem.cxx:2096
#4  0x00002adf5b7cb6bc in TUnixSystem::DispatchSignals(ESignals) () at /home/gluex/root/root-6.06.08/core/unix/src/TUnixSystem.cxx:3562
#5  <signal handler called>
#6  G4VoxelNavigation::ComputeStep(CLHEP::Hep3Vector const&, CLHEP::Hep3Vector const&, double, double&, G4NavigationHistory&, bool&, CLHEP::Hep3Vector&, bool&, bool&, G4VPhysicalVolume**, int&) () at /home/gluex/geant4/geant4.10.02.p02/source/geometry/management/include/G4VPhysicalVolume.icc:76
#7  0x00002adf58f4116d in G4Navigator::ComputeStep(CLHEP::Hep3Vector const&, CLHEP::Hep3Vector const&, double, double&) () at /home/gluex/geant4/geant4.10.02.p02/source/geometry/navigation/src/G4Navigator.cc:831
#8  0x00002adf58f48efe in G4PathFinder::DoNextLinearStep(G4FieldTrack const&, double) () at /home/gluex/geant4/geant4.10.02.p02/source/geometry/navigation/src/G4PathFinder.cc:926
#9  0x00002adf58f4b506 in G4PathFinder::ComputeStep(G4FieldTrack const&, double, int, int, double&, ELimited&, G4FieldTrack&, G4VPhysicalVolume*) () at /home/gluex/geant4/geant4.10.02.p02/source/geometry/navigation/src/G4PathFinder.cc:245
#10 0x00002adf5323c979 in G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength(G4Track const&, double, double, double&, G4GPILSelection*) () from /home/gluex/HDGeant4/tmp/Linux-g++/hdgeant4/libG4fixes.so
#11 0x00002adf564109e6 in G4SteppingManager::DefinePhysicalStepLength() () at /home/gluex/geant4/geant4.10.02.p02/source/processes/management/include/G4VProcess.hh:486
#12 0x00002adf5640e92f in G4SteppingManager::Stepping() () at /home/gluex/geant4/geant4.10.02.p02/source/tracking/src/G4SteppingManager.cc:180
#13 0x00002adf5641aa5c in G4TrackingManager::ProcessOneTrack(G4Track*) () at /home/gluex/geant4/geant4.10.02.p02/source/tracking/src/G4TrackingManager.cc:126
#14 0x00002adf5618d109 in G4EventManager::DoProcessing(G4Event*) () at /home/gluex/geant4/geant4.10.02.p02/source/event/src/G4EventManager.cc:184
#15 0x00002adf55f3467c in G4WorkerRunManager::ProcessOneEvent(int) () at /home/gluex/geant4/geant4.10.02.p02/source/run/src/G4WorkerRunManager.cc:253
#16 0x00002adf55f347f9 in G4WorkerRunManager::DoEventLoop(int, char const*, int) () at /home/gluex/geant4/geant4.10.02.p02/source/run/src/G4WorkerRunManager.cc:231
#17 0x00002adf55f26a2e in G4RunManager::BeamOn(int, char const*, int) () at /home/gluex/geant4/geant4.10.02.p02/source/run/src/G4RunManager.cc:273
#18 0x00002adf55f34d81 in G4WorkerRunManager::DoWork() () at /home/gluex/geant4/geant4.10.02.p02/source/run/src/G4WorkerRunManager.cc:619
#19 0x00002adf55f40714 in G4MTRunManagerKernel::StartThread(void*) () at /home/gluex/geant4/geant4.10.02.p02/source/run/src/G4MTRunManagerKernel.cc:191
#20 0x0000003858807aa1 in start_thread () from /lib64/libpthread.so.0
#21 0x00000038580e8bcd in clone () from /lib64/libc.so.6

**Comment by sdobbs** [comment]
This is a one-time problem, so the assumption is that a weird corner case (with the geometry?)

So for now, closing this.
