### ISSUE TITLE
Overall BCAL energy shift?

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/HDGeant4#113]
In his BCAL fiducial cut studies, Mark Dalton found that there was a difference in the peak positions of reconstructed/true photon energies between hdgeant versions of 0.93 in hdgeant4 and 0.97 in hdgeant.

<img width="603" alt="BCAL_g4_energies" src="https://user-images.githubusercontent.com/1182058/59388181-1ff03900-8d39-11e9-8101-988baaaa9096.png">
<img width="603" alt="BCAL_g3_energies" src="https://user-images.githubusercontent.com/1182058/59388182-1ff03900-8d39-11e9-9b11-b1ac3b118680.png">

 

This is different than the results reported by Richard Jones in his studies of energy calibration and needs to be reconciled.

**Comment by markdalton** [comment]
I ran 2 simulations (hdgeant and hdgeant4, both version 4.4.0) throwing single photons into the BCAL from 12 degrees to 90 degrees between 100 MeV and 6 GeV.  The distributions were logarithmic in angle and energy, roughly emulating the overall distribution of photons in the physics data.  

The files are located here:
/cache/halld/halld-scratch/REQUESTED_MC/ParticleGun/gamma_100_6000MeV_12_90deg_g3_20190627042045pm/
/cache/halld/halld-scratch/REQUESTED_MC/ParticleGun/gamma_100_6000MeV_12_90deg_g4_20190627042209pm/

All plots are of the energy fraction, the reconstructed energy divided by the thrown energy on a shower-by-shower basis.  The first plots show that there is an overall shift to lower energies in hdgeant4.  Fits to the core of the peaks give the following central values with negligible statistical uncertainty.
G3: 1.004 
G4: 0.979

![EfracN](https://user-images.githubusercontent.com/13302551/60460199-1ad42a80-9c11-11e9-85e0-43073779ae63.png)
![EfracN](https://user-images.githubusercontent.com/13302551/60460216-20ca0b80-9c11-11e9-8833-4c5f21a5019a.png)

The next plots show that this is not some portion of the phase space.  Every energy and every angle shows an overall shift.

![EfracN_EThrow_Theta_slicegaus_mean](https://user-images.githubusercontent.com/13302551/60460228-29badd00-9c11-11e9-8ff2-7be2b50d52a3.png)
![EfracN_EThrow_Theta_slicegaus_mean](https://user-images.githubusercontent.com/13302551/60460232-2d4e6400-9c11-11e9-8845-af48dd80e01a.png)

![EfracN_ThetaThrow_E_slicegaus_mean](https://user-images.githubusercontent.com/13302551/60460236-2fb0be00-9c11-11e9-8f05-97ae5e46a08f.png)
![EfracN_ThetaThrow_E_slicegaus_mean](https://user-images.githubusercontent.com/13302551/60460240-32abae80-9c11-11e9-89c0-228bfe3ba007.png)

The effect is clear and the magnitude is about 2.5% (when considering the difference between G3 and G4).  I advocate applying a this correction to hdgeant4.  I am open to other ways of extracting the exact size of the correction.

**Comment by markito3** [comment]
from Mark Dalton:

Subject: Re: [Halld-offline] HDGeant4 Meeting Minutes, July 2,  2019
Date: Tue, 2 Jul 2019 18:09:19 -0400
From: Mark-Macrae Dalton <dalton@jlab.org>
To: Hall D Software Group <halld-offline@jlab.org>

Dear All,

Apologies for missing the meeting today.

The main difference between my previous study and this recent one is the sample of photons that were thrown.  Previously I threw flat in angle and energy and went out to 10 GeV.  This time I threw log in angle and energy and only went out to 6 GeV.  The aim of these change was to make the sample more representative of the actual photons in the experiment.  I also changed the minimum angle from 11 degrees to 12 degrees to cut the transition region.

The versions of the simulation software are also different but this is likely much less important.

Best,
Mark

**Comment by markito3** [comment]
Richard has pointed out that the most recent plots do not agree with [results he presented in March](https://docs.google.com/presentation/d/1IDw4LD2GhBpzam9E1V8LRBcb49Kb1V3GMTWR2Inw2V8/edit#slide=id.p).

**Comment by rjones30** [comment]
Hello Mark and all,

I don't think there has been much action on the simulation front over the
past two weeks, and I have been on vacation for a good part of it. Does it
make sense to skip today's meeting unless someone has something urgent to
present?

-Richard

**Comment by markito3** [comment]
Makes sense to me. See you in two weeks.

**Comment by markdalton** [comment]
What's it going to take for this to get fixed?

**Comment by sdobbs** [comment]
We talked about this some at the last HDGeant4 meeting.  There aren't any
minutes at the moment, so maybe someone can remind me what the conclusion
was?
I think it might have been one of the issues that we are waiting for
Richard to get to.

---Sean

**Comment by nsjarvis** [comment]
I think we might have needed Mark and Richard to both be at the same
meeting?  Didn't Mark have a presentation on this from a while back?

Naomi.

**Comment by igjaegle** [comment]
in principle this was solved in #146
