### ISSUE TITLE
HDGeant4 does not use the run number embedded in the INFILE

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#115]
For compatibility with hdgeant, if the run number is not supplied in control.in or on the command line, HDGeant4 is supposed to use the run number embedded in the INFILE, if provided.  This is currently documented in control.in.

It does not do this, instead it sets run number=0 and crashes. 

I note that this would be a rare use-case, and one possible fix would be to change the documentation.

**Comment by rjones30** [comment]
Hello Naomi,

Yes, I see what you see. I have one (I hope) last PR on github for this
issue, waiting for your approval. I guess what I had called policy was a
combination of various ways I was using hdgeant and hdgeant4, without
checking for uniformity. This is a much cleaner behavior now, and
furthermore it agrees with the documentation!

-Richard J.

**Comment by nsjarvis** [comment]
Looks good now, thanks.
