### ISSUE TITLE
Segfault from G4VoxelNavigation::ComputeStep

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#117]
Segfault without error message, starting in thread 5.    HDGeant4 master from last week, which is the same as the more recent tag 2.4.0

Thread 5 (Thread 0x2b4b56001700 (LWP 47021)):

> #5  <signal handler called>
> #6  G4VoxelNavigation::ComputeStep(CLHEP::Hep3Vector const&, CLHEP::Hep3Vector const&, double, double&, G4NavigationHistory&, bool&, CLHEP::Hep3Vector&, bool&, bool&, G4VPhysicalVolume**, int&) () at /home/gluex/geant4/geant4.10.02.p02/source/geometry/management/include/G4VPhysicalVolume.icc:58

The attached files include

- the stack trace
- the last complete set (one for every thread) of HDGeant4's starting seeds, obtained from recompiling with VERBOSE_RANDOMS (I added the event number pev(0).getEventNo() to the printout from GlueXUserEventInformation::SetRandomSeeds in GlueXUserEventInformation.cc ) 
- the control.in file
- the event which caused the crash, extracted from the original hddm input using hddm_cull_events (using the event number obtained above)

[stacktrace_474619.txt](https://github.com/JeffersonLab/HDGeant4/files/3356213/stacktrace_474619.txt)

[seeds.txt](https://github.com/JeffersonLab/HDGeant4/files/3356214/seeds.txt)

[g4_41510_5000009_control.in.txt](https://github.com/JeffersonLab/HDGeant4/files/3356217/g4_41510_5000009_control.in.txt)

[bggen_5000009_event_1197497.hddm.txt](https://github.com/JeffersonLab/HDGeant4/files/3356218/bggen_5000009_event_1197497.hddm.txt)

**Comment by rjones30** [comment]
This issue should be revisited in view of the major fixes to multi-threaded G4 that were made, following on from issue #143

**Comment by nsjarvis** [comment]
I repeated this, using Geant 10.4.2 with HDGeant4 master from June 15, and it crashed with the Curve length mismatch reported as issue #109

**Comment by nsjarvis** [comment]
And using the helpful new debug info, I have: 

G4WT3 > New event 4013 with starting seeds 1608625920, 1519592825
G4WT3 > 
G4WT3 > 
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomNav0003
      issued by : G4PropagatorInField::ComputeStep()
Curve length mis-match between original state and proposed endpoint of propagation.
  The curve length of the endpoint should be: 45.1082
  and it is instead: 45.2994.
  A difference of: -0.191231
  Original state =  (  X= -58.4881665 -2.28316903 2715.19342  P= -0.0776937042 -0.000913346078 0.339966875  Pmag= 0.34873288 Ekin= 0.107656493 l= 0 m0= 0.510999 (Pdir-1)= 0 t_lab= -0.734 t_proper= 0 PolV= (0,0,0)  ) 
  Proposed state =  (  X= -58.3610813 -2.34475567 2759.34774  P= -0.039070404 0.0673481124 0.339929929  Pmag= 0.34873288 Ekin= 0.107656493 l= 45.2994090878 m0= 0.510999 (Pdir-1)= 0 t_lab= 0 t_proper= 0 PolV= (0,0,0)  ) 
*** Fatal Exception *** core dump ***
G4WT3 > G4Track (0x7fa4392cc410) - track ID = 3954, parent ID = 3672
G4WT3 >  Particle type : e- - creator process : hIoni, creator model : Undefined
G4WT3 >  Kinetic energy : 107.656 keV - Momentum direction : (-0.222789,-0.00261904,0.974863)
G4WT3 >  Step length : 0 fm  - total energy deposit : 0 eV 
G4WT3 >  Pre-step point : (-58.4882,-2.28317,2715.19) - Physical volume : LASS::1 (Air)
G4WT3 >  - defined by : not available
G4WT3 >  Post-step point : (-58.4882,-2.28317,2715.19) - Physical volume : LASS::1 (Air)
G4WT3 >  - defined by : eIoni - step status : 7
G4WT3 >  *** Note: Step information might not be properly updated.
G4WT3 > 
-------- EEEE -------- G4Exception-END --------- EEEE -------

G4WT3 > 
G4WT3 > *** G4Exception: Aborting execution ***

Lmk if you would like to see the troublesome event.  I am assuming not, as this is the same error seen elsewhere.

**Comment by rjones30** [comment]
Naomi,

Yes, thank you for reporting this error. Some interesting commonalities:
always in Air, always an electron or positron, always in LASS::1 or
BCAL::1, always step-limited by physics (eIoni, msc) not geometry
boundaries. These are important clues, closing in on it now.

-Richard Jones

**Comment by nsjarvis** [comment]
I don't know if this is clue or coincidence, but my 9 recent bggen jobs for run 50932 all completed successfully.   
The crashes that I found were from the earlier runs, 4nnnn.   At the previous crash rate I would have expected 1 or 2 of the new jobs to crash.

**Comment by nsjarvis** [comment]
Fixed by PR 165
