### ISSUE TITLE
Another segfault from G4VoxelNavigation::ComputeStep

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#118]
This looks like https://github.com/JeffersonLab/HDGeant4/issues/117

Segfault without error message, starting in thread 8.  HDGeant4 master from last week, which is the same as the more recent tag 2.4.0

Thread 8 (Thread 0x2acaea001700 (LWP 20060)):
> #5  <signal handler called>
> #6  G4VoxelNavigation::ComputeStep(CLHEP::Hep3Vector const&, CLHEP::Hep3Vector const&, double, double&, G4NavigationHistory&, bool&, CLHEP::Hep3Vector&, bool&, bool&, G4VPhysicalVolume**, int&) () at /home/gluex/geant4/geant4.10.02.p02/source/geometry/management/include/G4VPhysicalVolume.icc:58

The attached files include

- the stack trace
- the last complete set (one for every thread) of HDGeant4's starting seeds, obtained from recompiling with VERBOSE_RANDOMS (I added the event number pev(0).getEventNo() to the printout from GlueXUserEventInformation::SetRandomSeeds in GlueXUserEventInformation.cc )
- the control.in file
- the event which caused the crash, extracted from the original hddm input using hddm_cull_events (using the event number obtained above)

[stacktrace_474626.txt](https://github.com/JeffersonLab/HDGeant4/files/3356306/stacktrace_474626.txt)

[seeds.txt](https://github.com/JeffersonLab/HDGeant4/files/3356307/seeds.txt)

[g4_40946_5000011_control.in.txt](https://github.com/JeffersonLab/HDGeant4/files/3356312/g4_40946_5000011_control.in.txt)

[bggen_5000011_event_1116151.hddm.txt](https://github.com/JeffersonLab/HDGeant4/files/3356315/bggen_5000011_event_1116151.hddm.txt)

**Comment by rjones30** [comment]
This issue should be revisited in view of the major fixes to mutli-threaded G4 that were recently implemented, following on from issue #143

**Comment by nsjarvis** [comment]
A re-run of this results in the curve length mismatch

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomNav0003
      issued by : G4PropagatorInField::ComputeStep()
Curve length mis-match between original state and proposed endpoint of propagation.
  The curve length of the endpoint should be: 25.8865
  and it is instead: 25.9938.
  A difference of: -0.107332
  Original state =  (  X= 41.8014436 46.4366948 2141.14969  P= -0.0720298598 -0.0217346831 0.233739276  Pmag= 0.245549886 Ekin= 0.0559355063 l= 0 m0= 0.510999 (Pdir-1)= 0 t_lab= 6.47457 t_proper= 0 PolV= (0,0,0)  ) 
  Proposed state =  (  X= 41.7313869 46.3737067 2165.91302  P= -0.0669583125 -0.0344470928 0.233719337  Pmag= 0.245549886 Ekin= 0.0559355063 l= 25.9938461216 m0= 0.510999 (Pdir-1)= -1.11022e-16 t_lab= 0 t_proper= 0 PolV= (0,0,0)  ) 
*** Fatal Exception *** core dump ***
G4WT5 > G4Track (0x7fa4054d6300) - track ID = 2931, parent ID = 2607
G4WT5 >  Particle type : e- - creator process : eIoni, creator model : Undefined
G4WT5 >  Kinetic energy : 55.9355 keV - Momentum direction : (-0.293341,-0.0885143,0.951901)
G4WT5 >  Step length : 0 fm  - total energy deposit : 0 eV 
G4WT5 >  Pre-step point : (41.8014,46.4367,2141.15) - Physical volume : LASS::1 (Air)
G4WT5 >  - defined by : not available
G4WT5 >  Post-step point : (41.8014,46.4367,2141.15) - Physical volume : LASS::1 (Air)
G4WT5 >  - defined by : eIoni - step status : 7
G4WT5 >  *** Note: Step information might not be properly updated.

**Comment by nsjarvis** [comment]
Fixed by PR 165
