### ISSUE TITLE
Cannot rerun hdgeant4 with chosen seeds

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#119]
I need to run hdg4 using the same pair of seeds that generated the crash in issue 109, and I don't seem to be able to do so.  

I ran hdgeant4 providing a pair of starting seeds in control.in.  hdgeant4 ran using a different set of seeds.   When I supply the same pair repeatedly, hdgeant4 uses the same different set of seeds consistently.   From reading the instructions in control.in, I am not totally sure whether supplying a pair of seeds instructs hdg4 to use that pair of seeds directly as seeds, or to use the supplied pair to generate a sequence of seed pairs.   

My bggen event INFILE does not contain any seeds.    

I ran:
hdgeant4 -r 50000 < hdg4.in > seeds_1_2.out

In control.in I have: 
RNDM 1,2

grep seeds seeds_1_2.out gives
G4WT0 > New event 1219154 with starting seeds 1998275222, 1884429348

[control.in.txt](https://github.com/JeffersonLab/HDGeant4/files/3458615/control.in.txt)
[hdg4.in.txt](https://github.com/JeffersonLab/HDGeant4/files/3458618/hdg4.in.txt)
[testevent.hddm.txt](https://github.com/JeffersonLab/HDGeant4/files/3458619/testevent.hddm.txt)
[seeds_1_2.out.txt](https://github.com/JeffersonLab/HDGeant4/files/3458620/seeds_1_2.out.txt)

**Comment by nsjarvis** [comment]
Fixing this would help with the first step towards fixing issues 109, 117 and 118, which is to see if they are repeatable.

**Comment by rjones30** [comment]
Naomi,

The fields in the control.in file need to be space-separated, as far as I
know. You have this comma in there, do you have any examples showing
commas? I have never seen this done.

-Richard

**Comment by nsjarvis** [comment]
I tried again with 
RNDM 1 2 
and this produced 
G4WT0 > New event 1219154 with starting seeds 456040262, 153825144

so then I tried 
RNDM 1
and this gave
G4WT0 > New event 1219154 with starting seeds 1998275222, 1884429348
which is the same as when I had provided 1,2.   So you are right, the comma is not a good idea.   

I have not seen any examples at all.

**Comment by rjones30** [comment]
Hello Naomi,

Yes, you are right, the initialization of seeds from control.in was broken
in hdgeant4. Apparently somewhere along the way one of the developers
decided that they need to generate random numbers during setup prior to the
start of the first event simulation. This means that setting the initial
seeds from the main program does not work anymore. I have created a fix for
this and submitted a PR on github. If you want to merge the PR, and do git
pull you will be able to check whether this fix works for you.

thanks for reporting this,
-Richard Jones

**Comment by nsjarvis** [comment]
Yes!  Fixed in PR #120.  Thank you.
