### ISSUE TITLE
DIRC mirror reflectivity

### ISSUE THREAD

**Issue by yunjie-yang** [JeffersonLab/HDGeant4#121]
Hello experts,

We have a question about implementing wavelength-dependent reflectivity for the DIRC optical box mirrors. It seems that simply changing the "reflect" property within the optical_properties doesn't have any effects on the final photon yield.

Specifically, I created two versions of the material xml file in the yunjiey_dirc_mirror_reflectivity branch of hdds: Material_HDDS_v1.xml and Material_HDDS_v2.xml. The only difference between them should be that in the definition of "ThickCerenkovMirror" (which is the material for the mirrors in the optical box), v1 has some reasonable wavelength-dependent numbers for the "reflect" property whereas for v2 I simply put 0.0001 for wavelengths as the "reflect". However, they seem to produce the exact photon yield. I created a slightly modified truth_dirc plugin to quickly plot the photon yield (see below).

Here's some quick instruction that should reproduce what I am describing here:
0) I started with the current master branches of hdds, hdgeant4 and halld_recon
1) run hdgeant4 with the attached control file (a particle gun of pions hitting one bar)
[control.txt](https://github.com/JeffersonLab/HDGeant4/files/3532034/control.txt), and with one of the Material_HDDS_v1(2).xml file as the material file
2) compile the truth_dirc plugin with the .cc and .h files from the yunjiey_dirc_mirror_reflectivity branch of halld_recon (under halld_recon/src/plugins/Analysis/truth_dirc)
3) run this modified truth_dirc plugin on the hdgeant4 output, and the hNph histogram in the produced hd_root.root file is the photon yield distribution.

It seems that v1 and v2 produce the exact same distributions...

**Comment by rjones30** [comment]
Hello Yunjie,

It is possible that there is a bug in the library, although more likely
that the bug is in the geometry + optical properties description. This is a
good description you have assembled, complete with instructions for
reproducing it. Thank you for this, I am tied up with start-of-semester
work right now, but hope to get back to look at it within a couple of days.

-Richard Jones

**Comment by jrstevenjlab** [comment]
I dug into this a little bit and found that the material properties weren't getting set for the G4OpticalSurface in HddsG4Builder.  The pull request which (I believe) fixes the bug is PR #122

Yunjie, can you try this fix against your example?
Richard, can you check that I didn't introduce some other issue with this fix?

-Justin

**Comment by yunjie-yang** [comment]
Hi Justin,

I think this does the trick! I tried my example Materials_HDDS_v1(2).xml files. With v2 where I set the reflectivity to effectively 0, I indeed see effectively 0 detected photons at the PMTs. With v1 which is what's currently in the master (our implementation of the non-UVE version), the photon yield certainly moves in the right direction compared to previously.  The plot shows a comparison: [current_vs_fix.pdf](https://github.com/JeffersonLab/HDGeant4/files/3585599/current_vs_fix.pdf). The top row shows what's currently in the master and the bottom row shows this fix. 

Yunjie

**Comment by jrstevenjlab** [comment]
Thanks Yunjie.  Once Richard reviews and approves the fix we’ll merge it in.
-Justin

**Comment by rjones30** [comment]
Hello Yunjie and all,

I confirmed that Justin's fix for adding the material optical properties to
the OpticalSurface that defines reflective surfaces is correct. I have
pulled the change into the Master branch, so you should now be getting
behavior that is more consistent between geant3 and geant4. If you see
other differences that are significant, please post a new issue. As soon as
you are satisfied that the problem you originally reported has been
address, can you resolve the issue you created on github?

thank you,
-Richard Jones

**Comment by yunjie-yang** [comment]
Hi Richard,

Thank you confirming. We have tested this fix and it seems to behave as expected. We will continue our studies in more detail, but I think we can close this issue.

Thank you again!

Yunjie
