### ISSUE TITLE
Neutron Simulation

### ISSUE THREAD

**Issue by aaust** [JeffersonLab/HDGeant4#125]
I am trying to simulate a signal sample for the reaction gamma p -> pi+ pi+ pi- n. It works with geant3, but the latest version of hdgeant4 breaks with the error message:
```
*** G4Exception : DECAY003
      issued by : G4Decay::DoIt
 can not determine decay channel
*** Fatal Exception *** core dump ***
```
I made a small test setup to reproduce the issue. Just copy the following folder:
`/work/halld2/home/aaustreg/Analysis/simulation/n3pi/g4_bomb/`
and execute `hdgeant4 run.mac`

**Comment by jonzarling** [comment]
Thanks for making a github issue and testing area, I was encountering this too. For me I saw this in the reaction gamma p -> pi+ n. The error message is the same. It takes maybe on the order of 100 events or so to encounter this error. 

I would suspect that some secondary from neutron interactions is having trouble figuring out how to decay. Or possibly the neutron is struggling to decay, though that seems a lot less likely.

**Comment by jonzarling** [comment]
I can also confirm that this works ok for geant3

**Comment by karthik18495** [comment]
> I am trying to simulate a signal sample for the reaction gamma p -> pi+ pi+ pi- n. It works with geant3, but the latest version of hdgeant4 breaks with the error message:
> 
> ```
> *** G4Exception : DECAY003
>       issued by : G4Decay::DoIt
>  can not determine decay channel
> *** Fatal Exception *** core dump ***
> ```
> 
> I made a small test setup to reproduce the issue. Just copy the following folder:
> `/work/halld2/home/aaustreg/Analysis/simulation/n3pi/g4_bomb/`
> and execute `hdgeant4 run.mac`

I am trying to simulate gamma p -> Pi+ Eta Neutron. It also breaks down with similar error. Has this been addressed ? Thank you 
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : DECAY003
      issued by : G4Decay::DoIt
 can not determine decay channel 
*** Fatal Exception *** core dump ***
-------- EEEE -------- G4Exception-END --------- EEEE -------

G4WT2 > 
G4WT2 > *** G4Exception: Aborting execution ***
Abort

**Comment by T-Britton** [comment]
I believe that hdgeant4 doesn't know how  to decay neutrons... as far as I know this has not been addressed yet.


-------- Original message --------

**Comment by rjones30** [comment]
Something is wrong with your generated events. Alex and Jon, might you both be using the same buggy event generator? For example, here is the generated final state of event 1 in Alexander's gen_amp_030730_000.hddm sample:
<vertex>
        <product decayVertex="0" id="1" mech="0" parentid="0" pdgtype="2112" type="Neutron">
          <momentum E="1.03409" px="-0.259474" py="0.299212" pz="0.179231" />
        </product>
        <product decayVertex="0" id="2" mech="0" parentid="0" pdgtype="211" type="Pi+">
          <momentum E="4.58613" px="0.358609" py="-0.552886" pz="4.53639" />
        </product>
        <product decayVertex="0" id="3" mech="0" parentid="0" pdgtype="-211" type="Pi-">
          <momentum E="2.37669" px="-0.207191" py="0.189667" pz="2.3559" />
        </product>
        <product decayVertex="0" id="4" mech="0" parentid="0" pdgtype="211" type="Pi+">
          <momentum E="1.37405" px="0.108055" py="0.0640074" pz="1.36117" />
        </product>
        <origin t="0" vx="0" vy="0" vz="64.3702" />
      </vertex>

Let's look at this neutron: momentum E="1.03409" px="-0.259474" py="0.299212" pz="0.179231". If you compute the invariant mass of this neutron to the precision allowed here, you get 0.938277 MeV. This is not the mass of a neutron, this is the mass of a proton. Being too light, this neutron cannot conserve energy in its decay.

-Richard

**Comment by rjones30** [comment]
Hello Alexander and all,

Thank you for reporting the problem you are seeing with neutrons in
hdgeant4 and for providing a test case demonstrating this issue.

It seems that something is wrong with your event generator. Alex and Jon,
might you both be using the same buggy event generator? For example, here
is the generated final state of event 1 in Alexander's
gen_amp_030730_000.hddm sample:

`<vertex>
    <product decayVertex="0" id="1" mech="0" parentid="0"
pdgtype="2112" type="Neutron">
      <momentum E="1.03409" px="-0.259474" py="0.299212" pz="0.179231" />
    </product>
    <product decayVertex="0" id="2" mech="0" parentid="0"
pdgtype="211" type="Pi+">
      <momentum E="4.58613" px="0.358609" py="-0.552886" pz="4.53639" />
    </product>
    <product decayVertex="0" id="3" mech="0" parentid="0"
pdgtype="-211" type="Pi-">
      <momentum E="2.37669" px="-0.207191" py="0.189667" pz="2.3559" />
    </product>
    <product decayVertex="0" id="4" mech="0" parentid="0"
pdgtype="211" type="Pi+">
      <momentum E="1.37405" px="0.108055" py="0.0640074" pz="1.36117" />
    </product>
    <origin t="0" vx="0" vy="0" vz="64.3702" />
  </vertex>`

Let's look at this neutron: momentum E="1.03409" px="-0.259474"
py="0.299212" pz="0.179231". If you compute the invariant mass of this
neutron to the precision allowed here, you get 0.938277 MeV. This is not
the mass of a neutron, this is the mass of a proton. Being too light, this
neutron cannot conserve energy in its decay.

I propose adding a warning line in both hdgeant and hdgeant4 checking the
agreement between the PDG mass and the invariant mass of the final-state
particles in the input event. That would have saved me several hours of
effort trying to figure out how on earth neutrons with the wrong mass ended
up in the simulation!

-Richard

**Comment by T-Britton** [comment]
Good catch Richard!  Yes a warning would be good ("There be monsters").  So why does it work in geant3? Does Geant 3 not conserve energy?

I'll let Alex confirm, but Jon used gen_amp so even if they used different generators we should look into gen_amp for potential typos (ID 2212 vs 2112).  I poked my head into ParticleType.h and see "Neutron" has a mass of .939....

**Comment by rjones30** [comment]
The reason hdgeant did not complain is that it (silently) ignores the
energy specified for the particle in the input file, and uses only the
3-momentum and the particle type to specify the final state particles. In
hdgeant4, all 4 momentum components are taken from the input file, as you
would want if the particle were unstable enough to have an observable width.

-Richard Jones

**Comment by aaust** [comment]
I used the old gen_3pi generator, but it has the same code base as gen_amp. After looking into the code, I can confirm that the proton mass was used for the recoil particle. I will fix it and repeat the test.

**Comment by aaust** [comment]
I added a switch into gen_amp to select the right recoil particle:
https://github.com/JeffersonLab/halld_sim/pull/96

I also tried my old generated file after @rjones30's pull request  #129. hdgeant4 prints out the following warning now:
```
G4WT0 > === WARNING in GlueXPrimaryGeneratorAction::GeneratePrimaryVertex ===
G4WT0 >    neutron found in input MC record, geant3 type 13, PDG type 2112 has unphysical mass: 
G4WT0 >    expected 939.565 MeV, found 938.272 MeV, difference -1.29334 MeV
```
It still crashes after a while, but now we know why.

@jonzarling and @karthik18495 , can you please confirm that the update to halld_sim fixes your issue after my pull request is merged in.
