### ISSUE TITLE
Nuclear Target Support

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/HDGeant4#127]
Elton brought this up on the Google Software Help List, but just to keep track of the issue, we will need support for a range of nuclei that will be used as targets for completed/upcoming experiments (Be-Pb).

Some of these are defined in halld_recon (particleType.h), but we should come up with some coordinated way to add the rest.

**Comment by rjones30** [comment]
Hello,

Here is a list of the nuclear ions I have added support for in my new PR. I
think it looks like a good start

Deuteron
Tritium
Alpha
He3
Li6
Li7
Be7
Be9
B10
B11
C12
N14
O16
F19
Ne20
Na23
Mg24
Al27
Si28
P31
S32
Cl35
Ar36
K39
Ca40
Sc45
Ti48
V51
Cr52
Mn55
Fe56
Co59
Ni58
Cu63
Zn64
Li6
Li7
Be7
Be9
B10
B11
C12
N14
O16
F19
Ne20
Na23
Mg24
Al27
Si28
P31
S32
Cl35
Ar36
K39
Ca40
Sc45
Ti48
V51
Cr52
Mn55
Fe56
Co59
Ni58
Cu63
Zn64
Ge74
Se80
Kr84
Sr88
Zr90
Mo98
Pd106
Cd114
Sn120
Xe132
Ba138
Ce140
Sm152
Dy164
Yb174
W184
Pt194
Au197
Hg202
Pb208
U238

-Richard Jones

**Comment by sdobbs** [comment]
Yes, I think this is good enough for now and we can close the issue.
