### ISSUE TITLE
BCAL Reconstructed Energy skewed in runs less than 40000

### ISSUE THREAD

**Issue by jonzarling** [JeffersonLab/HDGeant4#138]
The reconstructed energy in the has a long, non-gaussian tail in run numbers before 40000 in geant4. Geant3 simulations and using run numbers of 40000+ appear fine. I shot a photon gun at a fixed energy of either 1 or 2 GeV, 60 degrees theta, uniform phi, and fixed position in the target. Seems consistent over different energies, theta, software versions (tried on jlab and offsite), and several run numbers.

![image](https://user-images.githubusercontent.com/17165552/71289781-fc3b2a80-233b-11ea-86f4-4440b4c39c08.png)
![image](https://user-images.githubusercontent.com/17165552/71289792-02310b80-233c-11ea-8f3a-dfcf4d1b2f48.png)
![image](https://user-images.githubusercontent.com/17165552/71289805-0a894680-233c-11ea-8f89-d510e6a9b30d.png)
![image](https://user-images.githubusercontent.com/17165552/71289807-0e1ccd80-233c-11ea-9ce5-1f4b33e0022d.png)

**Comment by jonzarling** [comment]
It would be nice if someone could replicate the issue. I'd be concerned that spring 2017 may be affected, maybe looking at the pulls would quickly evaluate that.

**Comment by rjones30** [comment]
Jon,

Ok, so THAT is what a calorimeter response looks like! Something may be
screwed up with that earlier run period, will check that out pronto.

-Richard

**Comment by jonzarling** [comment]
Thanks!

**Comment by markdalton** [comment]
I had a quick look at the simulation file that Jon provided 
/w/halld-scifs17exp/home/jzarling/MCGEN/1GeV_60deg/1.0/hddm/particle_gun_photon_gun_E_scan_030300_000_geant4_smeared.hddm

What I noticed is that there is a low occupancy region of the detector in phi which I find worrying. 
![bcal_cluster_phi](https://user-images.githubusercontent.com/13302551/71293133-6a82eb80-2342-11ea-89af-311c68f2e1e6.png)
![bcal_fadc_occ](https://user-images.githubusercontent.com/13302551/71293134-6a82eb80-2342-11ea-8c20-683b372a5330.png)

However, it's not clear to me whether this is related to Jon's problem or not.  The average energy for each channel doesn't show a big discontinuity as a function of phi.  
![bcal_point_aveE_sector_layer1](https://user-images.githubusercontent.com/13302551/71293135-6a82eb80-2342-11ea-8fdb-867c5c5f72e9.png)
![bcal_point_aveE_sector_layer2](https://user-images.githubusercontent.com/13302551/71293136-6b1b8200-2342-11ea-847e-cd8631f49698.png)
![bcal_point_aveE_sector_layer3](https://user-images.githubusercontent.com/13302551/71293137-6b1b8200-2342-11ea-958c-1aafdb07cc93.png)
![bcal_point_aveE_sector_layer4](https://user-images.githubusercontent.com/13302551/71293138-6b1b8200-2342-11ea-8915-50b1c1645069.png)

I don't understand why these plots show energy appearing to change smoothly with phi.  The occupancy at the hit level appears to have the same smooth effect (with the bite also taken out.)
![bcal_fadc_digi_occ_layer2](https://user-images.githubusercontent.com/13302551/71293767-6ce64500-2344-11ea-8799-a0f0a30ca22a.png)

**Comment by jonzarling** [comment]
Looks like the non-flat phi distribution is an artifact of the generation, the thrown distribution also carries this non-uniformity. This might arise from the fact that I generated a sample of events with an average phi=0 and Gaussian full width of 1,000 degrees. Although the Gaussian width is quite large, it's apparently still quite noticeable.

![image](https://user-images.githubusercontent.com/17165552/72379051-a52d3900-36e0-11ea-9242-bc13b4428b1c.png)


I'll verify that setting the mean phi to 180 degrees moves also moves these plots by the same phase, if so then the phi occupancy is not a cause for concern.

**Comment by jonzarling** [comment]
It turns out that the issue I was reporting here is NOT dependent on run number. That was a false correlation. After running more jobs, I see that the issue is (best that I can tell) randomly either working or broken from job startup. See https://github.com/JeffersonLab/HDGeant4/issues/143 for more info. 

To avoid confusion, I'm closing this issue and I would suggest we use the other issue linked instead.
