### ISSUE TITLE
Back compatibility issue?

### ISSUE THREAD

**Issue by igjaegle** [JeffersonLab/HDGeant4#144]
Use local HDDS with old TOF geometry to simulate run #30946

Crash error message:

G4WT1 > GlueXSensitiveDetectorFTOF::ProcessHits error - hdds geometry for FTOF is missing paired_row identifier, cannot continue!
*** Error in `hdgeant4': double free or corruption (out): 0x00002ab8b067fce0 ***

**Comment by sdobbs** [comment]
I think this is my fault, since I sent you the wrong prescription.
There were some extra tags added to the old XML file that I forgot
about.

Try getting the XML file you want by using:
ccdb dump GEOMETRY/ForwardTOF_HDDS.xml:30946

---Sean

**Comment by igjaegle** [comment]
Indeed the problem was that I used the wrong old TOF geometry. With the correct old TOF geometry, there is no error.
