### ISSUE TITLE
SKIP card is broken with sufficiently large numbers of events

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/HDGeant4#145]
hdgeant4 crashes if the SKIP card with a large number of events is used.  It looks like this might be a problem with the skip() function in the HDDM library?

This function is used heavily by MCWrapper when processing HDDM files containing generated 4 vectors that are passed to it.

This problem can be reproduced with the following files in /work/halld/home/sdobbs/as_mc 
Feb2020_AdRej_ee.hddm
control.in

**Comment by sdobbs** [comment]
Note that using SKIP with 200000 events will yield a stack trace  on segfault of about 200000 deep.

**Comment by T-Britton** [comment]
I should add that it appears "large" may be on the order of 10000

**Comment by rjones30** [comment]
Hello,

I have reproduced the problem, will have a fix submitted to github within
24 hours.

-Richard

**Comment by sdobbs** [comment]
Works great, thanks!
