### ISSUE TITLE
Start Counter Geometry

### ISSUE THREAD

**Issue by zihlmann** [JeffersonLab/HDGeant4#150]
The start counter geometry is still wrong in hdview2, it is off in phi by pretty much one counter in the display.

**Comment by markito3** [comment]
Who remembers that we should have had the target guys fix this before anything was installed?

**Comment by zihlmann** [comment]
As far as I remember we decided to not touch the physical detector.

**Comment by sdobbs** [comment]
This is a just a problem in hdview2, though, not the actual simulation?

**Comment by markito3** [comment]
I know. I'm saying that we should have touched the physical detector!

**Comment by staylorjlab** [comment]
Right -- we never fixed the display in hdview2.
________________________________

**Comment by sdobbs** [comment]
So this is a halld recon issue and not hdgeant4 right?

**Comment by staylorjlab** [comment]
Right.  In fact the geometry in the actual reconstruction is correct (reads from the xml).
________________________________
