### ISSUE TITLE
Energy deposition in TOF mismatch in data & MC

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/HDGeant4#159]
The issue noted in JeffersonLab/halld_sim#128 may require an update in how TOF hit attenuation is handled in HDGeant4.

**Comment by rjones30** [comment]
https://github.com/JeffersonLab/halld_sim/issues/128#issuecomment-653777991

**Comment by rjones30** [comment]
https://github.com/JeffersonLab/halld_sim/issues/128#issuecomment-653778841

**Comment by rjones30** [comment]
https://github.com/JeffersonLab/halld_sim/issues/128#issuecomment-653779972

**Comment by rjones30** [comment]
I believe that this issue has been addressed, and can be closed.
-Richard

**Comment by sdobbs** [comment]
closing as discussed in halld_sim
