### ISSUE TITLE
G4 exceptions for certain run numbers

### ISSUE THREAD

**Issue by T-Britton** [JeffersonLab/HDGeant4#167]
Elton submitted some bggen without background for runnumber 72301.  On the OSG it crashes in hd_root but with the same software on scosg16 it crashes in mcsmear.  But only after some G4 exceptions.

what I know right now; I am running /group/halld/www/halldweb/html/halld_versions/recon-2017_01-ver03_18.xml and G4 gives these :
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomNav0003
      issued by : G4Navigator::GetLocalExitNormal()
Function called when *NOT* at a Boundary.
Exit Normal not calculated.*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------G4WT0 >
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomNav0003
      issued by : G4Navigator::GetLocalExitNormal()
Function called when *NOT* at a Boundary.
Exit Normal not calculated.*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------G4WT0 >
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomNav0003
      issued by : G4Navigator::GetLocalExitNormal()
Function called when *NOT* at a Boundary.
Exit Normal not calculated.*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------G4WT0 >
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomNav0003
      issued by : G4Navigator::GetLocalExitNormal()
Function called when *NOT* at a Boundary.
Exit Normal not calculated.*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

Then mcsmear crashes with:
src/JANA/JEventLoop.cc:698  EXCEPTION : vector::_M_range_check
src/JANA/JApplication.cc:1386  EXCEPTION caught for thread 140251324937984 : std::exception

the number of events written changes every run and I think it may be correlated with the "first occurrence" of the G4 exception.  The same software with a different run number shows no issue (or the issue is at such a small rate as to not be detected in roughly 20k events). A set of files which produce the crash are located at scosg16:/osgpool/halld/tbritton/TestProj_1139

Elton will post a follow up with more info

**Comment by eltonssmith** [comment]
Here is more information on the submit issues when I run on the JLab farm.
- The submit jobs can be found in /work/halld2/home/elton/bggen
- The output files are all found in /work/halld/home/elton/bggen. The log entries are in the /log subdirectory

I have submitted 4M events and only about 70% of the jobs complete. My failed jobs seem to proceed through mcsmear but then crash in the analysis with "Exit code: 70".

------------ Submit directory
ifarm1802:bggen>pwd
/w/halld-scifs17exp/halld2/home/elton/bggen
ifarm1802:bggen>ls -ltr
total 34
-rw-r--r-- 1 elton halld-2  961 Jul 15 14:30 jana_bggen.config
-rw-r--r-- 1 elton halld-2  768 Jul 15 14:34 bggen_config.template
-rwxr-xr-x 1 elton halld-2 3605 Jul 15 16:23 MC.config~
-rwxr-xr-x 1 elton halld-2 3690 Jul 27 14:55 MC.config
ifarm1802:bggen>
ifarm1802:bggen>

Command to submit jobs are the following:
ifarm1802:bggen>$MCWRAPPER_CENTRAL/gluex_MC.py MC.config 72362 2000000 base_file_number=0 batch=1

**Comment by sdobbs** [comment]
Hi Elton, 
Regarding your running on the farm, I think your HDGeant4 version is fairly out of date, which could have some bearing on the errors you are getting.

**Comment by sdobbs** [comment]
Hi, I think I know the problem here - if you are using the version of halld_recon used for reconstructing the 2017 data, this will not work with the current run period, since it does not support the new TOF geometry.

You should probably use the latest version of the software stack that is available.

I'll think if a more useful error message can be printed out.

**Comment by rjones30** [comment]
Elton, did Sean's suggestion solve this issue for you? If so, can you close it?
-Richard

**Comment by markito3** [comment]
No responses about the status of this issue from @T-Britton or @eltonssmith recenly. Closing.
