### ISSUE TITLE
hdgeant4 hanging at first event

### ISSUE THREAD

**Issue by igjaegle** [JeffersonLab/HDGeant4#169]
Using a local halld_recon/sim and hdgeant4 in sync w/ the master branch. For whatever event generator, the simulation is stuck a the first event.

G4WT0 > Info: RF reference plane set to 65 cm.
G4WT0 > New event 1 with starting seeds 1800229218, 1692052461

**Comment by rjones30** [comment]
igale,

We are still without power here at home in Connecticut, which complicates
working from home somewhat, but this problem remains near the top of my
list. Predictions are we should have power back by the weekend. We shall
see.

-Richard Jones

**Comment by rjones30** [comment]
We have power back, looking at this problem now.
-Richard

**Comment by rjones30** [comment]
I believe that this issue is resolved. Please close if you agree.

**Comment by igjaegle** [comment]
The problem is solved.
