### ISSUE TITLE
Run number propagation problems

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/HDGeant4#17]
When running over events generated with an external generator (e.g. bggen), the run number set for those events is not propagated into HDGeant4.  Unless I missed some change, I believe the policy was that if the run number was not explicitly set in the control.in, it should be obtained from the events in the input file.

**Comment by rjones30** [comment]
Sean,

I submitted a pull request that corrects this behavior. It now should leave
the runno alone unless you override it in your control.in file. Go ahead
and accept my pull request if you agree with this change.

-Richard

**Comment by sdobbs** [comment]
Richard,
Thanks, I'll check this out.  The pull request is for your repository, I take it?

**Comment by rjones30** [comment]
Woops, no. I will correct the pull request.

**Comment by rjones30** [comment]
Sean, ok, now the PR should be with respect to the correct base. Confirm
and accept.

-rtj

**Comment by sdobbs** [comment]
Richard,

I am still seeing the problem.  Here are some example files at JLab that I am using:
In /lustre/expphy/work/halld/home/sdobbs/simtest
bggen.hddm
control.in

And some example screen output:

ifarm1402.jlab.org> hdgeant4 run.mac
Warning - no run number specified in control.in, default value of 0 assumed.

*************************************************************
 Geant4 version Name: geant4-10-02-patch-02 [MT]   (17-June-2016)
  << in Multi-threaded mode >> 
                      Copyright : Geant4 Collaboration
                      Reference : NIM A 506 (2003), 250-303
                            WWW : http://cern.ch/geant4
*************************************************************

JANA >>Created JCalibration object of type: JCalibrationCCDB
JANA >>Generated via: JCalibration using CCDB for MySQL and SQLite databases
JANA >>Run:0
JANA >>URL: mysql://ccdb_user@hallddb.jlab.org/ccdb
JANA >>context: default
JANA >>Reading Magnetic field map from Magnets/Solenoid/solenoid_1200A_poisson_20140520 ...
 Nx=251 Ny=1 Nz=701 )  at 0x2ed2f50
Reading fine-mesh B-field data from /group/halld/www/halldweb/html/resources/Magnets/Solenoid/finemeshes/solenoid_1200A_poisson_20140520.evio

[...]

**Comment by rjones30** [comment]
Sean, what run number are you seeing in the hdgeant.hddm output file?

-Richard J.

**Comment by rjones30** [comment]
Sean,

Looks like you flushed the PS files before my copy finished, a shame
because I had only 10% left to go. Guess I have to pull them back now by
hand, right?

-Richard J.

**Comment by sdobbs** [comment]
Richard,
I rebuilt from scratch and the bug is solved, so I will close this issue.
In regards to the PS skims, I think I originally pinned them for 14 days, so the pins likely timed out. You'll have to request them again, but please don't grab them all from tape at once - we only have about 20 TB of pins available, which is the less than than the total size of all PS skims from this run period.

**Comment by rjones30** [comment]
Sean, ok thanks for fetching them for me. I will get them later on, this
gives me enough to work with for the time being.
-Richard
