### ISSUE TITLE
Negative counts on eta invariant mass spectrum for 2017 simulation

### ISSUE THREAD

**Issue by KMahmoud** [JeffersonLab/HDGeant4#173]
Please see the attached plots. KinFit quantities are used.
[hdgeant_8_11_2020.pdf](https://github.com/JeffersonLab/HDGeant4/files/5059191/hdgeant_8_11_2020.pdf)

**Comment by KMahmoud** [comment]
Measured quantities does not show this negative counts. See the figures
[BE_Etamass_Measured.pdf](https://github.com/JeffersonLab/HDGeant4/files/5098388/BE_Etamass_Measured.pdf)
[BE_Etamass_Measured.pdf](https://github.com/JeffersonLab/HDGeant4/files/5098392/BE_Etamass_Measured.pdf)
[Eta_mass_Measured.pdf](https://github.com/JeffersonLab/HDGeant4/files/5098393/Eta_mass_Measured.pdf)

**Comment by sdobbs** [comment]
Thanks, that's interesting - is there a difference in the weights used or how you are handling the combinatorics between the measured and kinfitted quantities?

**Comment by KMahmoud** [comment]
No, there is no difference at all in the weights nor in handling the combinatorics.

**Comment by KMahmoud** [comment]
I'm closing this issue because Justin helped me figuring out the origin of the problem. In my code I have a double uniqueness tracking, one on the missing mass, and the second is on the final state photons only, which is not correct to use with the accidental subtraction.
