### ISSUE TITLE
Run number is changing to 10000 for whatever run used

### ISSUE THREAD

**Issue by igjaegle** [JeffersonLab/HDGeant4#177]
Resulting in exiting mcsmear because there are no calibration for CDC for run 10000

Software used: latest master branches for:
halld_recon
halld_sim
hdgeant4
mcwrapper

1 and 1
RUNNING MCSMEAR
running MCsmear without folding in random background
JANA >> Enabling z compression of output HDDM file stream (default)
JANA >> Enabling CRC data integrity check in output HDDM file stream
JANA >>Launching threads .
JANA >>Installing special signal handler for mcsmear...
JANA >>Opening source "genEtaRegge_030496_985_geant4.hddm" of type: HDDM
JANA >>Created JCalibration object of type: JCalibrationCCDB
JANA >>Generated via: JCalibration using CCDB for MySQL and SQLite databases
JANA >>Run:10000
JANA >>URL: mysql://ccdb_user@hallddb-farm.jlab.org/ccdb
JANA >>context: variation=mc
JANA >>comment: Variation for simulations with data conditions
JANA >>checking context = variation=mc
get BCAL/bcal_smear_parms_v2 parameters from CCDB...
Get BCAL/digi_scales parameters from CCDB...
Get BCAL/base_time_offset parameters from CCDB...
Get BCAL/channel_mc_efficiency tables from CCDB...
Get BCAL/ADC_saturation parameters from CCDB...
Get BCAL/SiPM_saturation parameters from CCDB...
JANA >>Creating DGeometry:
JANA >>  Run requested:10000  found:10000
JANA >>  Run validity range: 10000-10000
JANA >>  URL="ccdb:///GEOMETRY/main_HDDS.xml"  context="variation=mc_JEF"
JANA >>  Type="JGeometryXML"

**Comment by aaust** [comment]
That is the same as issue #175 , which was supposed to be fixed by PR #176

**Comment by rjones30** [comment]
I do not use or maintain MCwrapper, so I cannot verify it, but the
underlying problem with hdgeant4 has been fixed. If the problem persists,
maybe someone who works with mcwrapper can handle this?

-Richard J.

**Comment by T-Britton** [comment]
Richard means me :)

Did the method of passing in the run number change?  Also I would switch to the DEV branch of MCwrapper as master is more of a "latest release", this allows me to be more nimble in fixing things.

**Comment by sdobbs** [comment]
@igjaegle - do you have any of the output files from this run?  We should be able to at least check to make sure that this problem still occurs when running hdgeant4/mcsmear by hand.

**Comment by igjaegle** [comment]
I erased everything, but I will run test jobs in a hour or two.

tks ig.

**Comment by igjaegle** [comment]
You can an example output here:
/work/halld/home/ijaegle/30496_0

**Comment by rjones30** [comment]
This is not a hdgeant4 bug. Your input file genEtaRegge_030496_000.hddm has 30496 in the filename, but inside the file the run number is set to 10000. The filename actually has no meaning in hdgeant4. The run number is written into the individual events. You can name the file anything, it will make no difference.
-Richard Jones

<?xml version="1.0" encoding="UTF-8"?>
<HDDM class="s" version="1.0" xmlns="http://www.gluex.org/hddm">
  <physicsEvent eventNo="1" runNo="10000">
    <reaction type="0" weight="0">
      <beam type="Photon">
        <momentum E="8.33433" px="0" py="0" pz="8.33433" />
        <properties charge="0" mass="0" />
      </beam>
      <target type="Proton">
        <momentum E="0.938272" px="0" py="0" pz="0" />
        <properties charge="1" mass="0.938272" />
      </target>

**Comment by rjones30** [comment]
I propose that this issue can be closed.
-Richard

**Comment by igjaegle** [comment]
It appears to be an issue only with genEtaRegge. So I will closed this
issue.
