### ISSUE TITLE
crash with version set 5.3.0

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#204]
The files necessary to reproduce this are on /work/halld/njarvis/g4test.   
`[njarvis@ifarm1802.jlab.org: ~/mywork/g4test ]> which hdgeant4
/group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/hdgeant4/hdgeant4-2.32.0^hdr4330/bin/Linux-g++/hdgeant4

[njarvis@ifarm1802.jlab.org: ~/mywork/g4test ]> hdgeant4 hdg4.in

**************************************************************
 Geant4 version Name: geant4-10-04-patch-02 [MT]   (25-May-2018)
  << in Multi-threaded mode >> 
                       Copyright : Geant4 Collaboration
                      References : NIM A 506 (2003), 250-303
                                 : IEEE-TNS 53 (2006), 270-278
                                 : NIM A 835 (2016), 186-225
                             WWW : http://geant4.org/
**************************************************************

JANA >>Created JCalibration object of type: JCalibrationCCDB
JANA >>Generated via: JCalibration using CCDB for MySQL and SQLite databases
JANA >>Run:41510
JANA >>URL: mysql://ccdb_user@hallddb.jlab.org/ccdb
JANA >>context: default
JANA >>comment: Default constants for analyzing data
JANA >>Reading Magnetic field map from Magnets/Solenoid/solenoid_1350A_poisson_20160222 ...
 Nx=221 Ny=1 Nz=701 )  at 0x46b9470
Reading fine-mesh B-field data from /group/halld/www/halldweb/html/resources/Magnets/Solenoid/finemeshes/solenoid_1350A_poisson_20160222
 rmin: 0 rmax: 88.5 dr: 0.1 zmin: 0 zmax: 600 dz: 0.1
 Number of points in z = 6000
 Number of points in r = 885
 G4HelixMixedStepper: G4ClassicalRK4 chosen as stepper for small steps in G4HelixMixedStepper.
JANA >>154921 entries found (Creating DGeometry:
JANA >>  Run requested:41510  found:41510
JANA >>  Run validity range: 41510-41510
JANA >>  URL="ccdb:///GEOMETRY/main_HDDS.xml"  context="default"
JANA >>  Type="JGeometryXML"
JANA >>Found 25 material maps in calib. DB
JANA >>Read in 25 material maps for run 41510 containing 76153 grid points total
JANA >>
JANA >>Reading Pair Spectrometer Magnetic field map from Magnets/PairSpectrometer/PS_1.8T_20150513_test ...
 Nx=40 Ny=1 Nz=121 )  at 0x581f820
Initializing the Geant4 kernel...
Root geometry volume SITE::1 configured as World
 G4HelixMixedStepper: G4ClassicalRK4 chosen as stepper for small steps in G4HelixMixedStepper.
STC: ALL parameters loaded from ccdb
CDC: ALL parameters loaded from ccdb
FDC: ALL parameters loaded from ccdb
BCAL: ALL parameters loaded from ccdb
FTOF: ALL parameters loaded from ccdb
FCAL: ALL parameters loaded from ccdb
Warning from GlueXDetectorConstruction::ConstructSDandField - unsupported sensitive volume TAC1 found in geometry definition.
Additional geometry layer configured as ParallelWorld1
 G4PhysicsListHelper::AddTransportation()--- G4CoupledTransportation is used 
 New QGSP_FTFP_BERT physics list, replaces LEP with FTF/P for p/n/pi (/K?)  Thresholds: 
    1) between BERT  and FTF/P over the interval 6 to 8 GeV. 
    2) between FTF/P and QGS/P over the interval 12 to 25 GeV. 
  -- quasiElastic was asked to be 1
     Changed to 1 for QGS  and to 0 (must be false) for FTF
GlueXBeamConversionProcess::InitialiseProcess:
   Setting up cross section tables, please wait... finished.
G4WT0 > Opened input file: bggen_41510_100.hddm
G4WT0 > Warning from GlueXDetectorConstruction::ConstructSDandField - unsupported sensitive volume TAC1 found in geometry definition.
hdgeant4: src/GlueXPrimaryGeneratorAction.cc:888: void GlueXPrimaryGeneratorAction::GeneratePrimariesHDDM(G4Event*): Assertion `fPhotonBeamGenerator != 0' failed.
Abort`

**Comment by nsjarvis** [comment]
Richard told me that the crash is because my BEAM card is missing (commented out).

I wondered about that but thought it should be ok, because I am supplying an INFILE and the default control.in file says,
'c The order of the list is significant, that is if INFILE is present then the
c BEAM and KINE cards are ignored, otherwise if BEAM is present then KINE is
c ignored.' 

The program did not crash after I uncommented the BEAM card.  I was using an old control.in purely to run hdg4 long enough to download any new resource files, I don't have a random trigger, I'm not doing anything with the output.   

My complaint is now that the helpful text in control.in is outdated.

**Comment by rjones30** [comment]
This issue was addressed by a recent pull request. Please confirm that this meets the need, and close the issue if so.

**Comment by aaust** [comment]
Addressed by #208
