### ISSUE TITLE
CDC integrated charge shifted to higher values

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/HDGeant4#51]
Looking at the raw output of HDGeant4, it looks like the integrated charge determined for CDC hits is systematically shifted to higher values compared to HDGeant.  

Example MC data files and the input files used to create them are stored at:
http://hadron.physics.fsu.edu/~sdobbs/hdgeant4_tests/

The below histograms can be generated by running the following command:
python cdc_q.py hdgeant_g3_20k.hddm hdgeant_g4_20k.hddm

![cdc_q_hd](https://user-images.githubusercontent.com/1182058/41245361-dad5f852-6d75-11e8-9747-75bbb295fd4d.png)
![cdc_q_hd4](https://user-images.githubusercontent.com/1182058/41245360-daaecdd6-6d75-11e8-8ab2-0aebda6ef186.png)

![cdc_q_straw_hd](https://user-images.githubusercontent.com/1182058/41245386-e4ea55fe-6d75-11e8-8fa2-c99521f3e10f.png)
![cdc_q_straw_hd4](https://user-images.githubusercontent.com/1182058/41245385-e4d0924a-6d75-11e8-9249-eaf34382699c.png)

**Comment by rjones30** [comment]
Sean, can you overlay these two distributions? My eye tells me that there is no shift between the two distributions, but hdgeant4 simply drops the hit if it is below a certain minimum energy distribution. If the only difference is the suppression of hits with very low amplitudes in hdgeant4, this is not really a difference, is it? -Richard

**Comment by rjones30** [comment]
All follow-up on this issue will be with Issues Tracker under
JeffersonLab/hdgeant4 on github.
-Richard Jones

**Comment by sdobbs** [comment]
Richard,  I've attached the overlay plot you asked for (HDGeant=blue, HDGeant4=red).  Note that the CDC wire thresholds are wire dependent, but are around 500 in these units.

It occurred to me that this difference might be related to the different time distributions in both simulations, and indeed, HDGeant4 doesn't have this region of hits with large times and small integrated charge.  This is probably a good thing.

I was worried that this could affect some efficiency related to hit shadowing of merged background hits, but I think I convinced myself that this is not a problem. 

![cdc_q_overlay](https://user-images.githubusercontent.com/1182058/41321451-02b18c04-6e72-11e8-9a46-199a01aa2c23.png)
![cdc_t_q_hd](https://user-images.githubusercontent.com/1182058/41321822-b0129ae0-6e73-11e8-83bb-482b2d7a68e1.png)
![cdc_t_q_hd4](https://user-images.githubusercontent.com/1182058/41321823-b19eeca6-6e73-11e8-89b2-ec9b85988c88.png)

**Comment by rjones30** [comment]
Sean, do you know what is the origin of these excess low-amplitude CDC hits in hdgeant? They look like they are all piled up around 700ns in time. Does this point to a bug in hdgeant hits generation, rather than hdgeant4? -Richard

**Comment by sdobbs** [comment]
Richard,  Here is a comparison of the CDC hit efficiency plots as a function of DOCA to the wire, using our standard code (blue=HDGeant, red=HDGeant4).  It seems like the agreement between both simulations is indeed pretty good except at large distance.  Presumably HDGeant4 is more accurate, from the above observations.


![mc_eff_comp](https://user-images.githubusercontent.com/1182058/41366610-a151d998-6f0a-11e8-8f23-88057e1131fb.png)
![mc_eff_comp-ratio](https://user-images.githubusercontent.com/1182058/41366611-a3d84ada-6f0a-11e8-98b6-2c80bf4b356a.png)
