### ISSUE TITLE
TOF hit time distribution shape

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/HDGeant4#52]
Looking at the raw output of HDGeant4, it looks like the overall distribution of TOF truth hits has a different shape compared to that generated by HDGeant.  It looks like in HDGeant4, the central Gaussian is wider, with tails that fall off faster.

Example MC data files and the input files used to create them are stored at:
http://hadron.physics.fsu.edu/~sdobbs/hdgeant4_tests/

The first two histograms below (among others) can be generated by running the following command:
python tof_t.py hdgeant_g3_20k.hddm hdgeant_g4_20k.hddm
Several other histograms can be found in the attached ROOT files.

The script tof_t_diff.py also produces some other comparisons.  I'm not sure if the comparisons make sense or not - the attempt was to compare the same tracks from different HDGeant versions.  The TOF truth hits that are generated appear to vary approximately Gaussianly with a sigma ~1 ns between both HDGeant versions (see third histogram below).  The TOF truth point difference shows a similar spread.

![tof_truth_time_hd](https://user-images.githubusercontent.com/1182058/41260190-6bcc5bc0-6da4-11e8-9543-8e9992dddca5.png)
![tof_truth_time_hd4](https://user-images.githubusercontent.com/1182058/41260193-6d3fdf18-6da4-11e8-84b4-6e9845b8ad89.png)
![tof_truth_time_difference](https://user-images.githubusercontent.com/1182058/41260199-6f0d774c-6da4-11e8-8a5d-e207294a9aef.png)

[tof_diff.root.zip](https://github.com/JeffersonLab/HDGeant4/files/2091926/tof_diff.root.zip)
[tof.root.zip](https://github.com/JeffersonLab/HDGeant4/files/2091927/tof.root.zip)

**Comment by rjones30** [comment]
Sean, like in the case of the CDC hits above, you should make a minimum energy cut before the comparison. The total number of hits is larger in hdgeant than hdgeant4, leading me to believe that there is a low-energy cutoff in hdgeant4 that is not there in hdgeant, again having no real effect on the observed hits when a reasonable online threshold is applied. -Richard

**Comment by rjones30** [comment]
Hello all,

Follow-up on this issue is ongoing on the Issue Tracker feature of github
under JeffersonLab/hdgeant4.

-Richard Jones

**Comment by sdobbs** [comment]
Richard, below are some dE plots - not sure what is going on with the HDGeant one, but the HDGeant4 seems to show a clear MIP peak, which is good to see.  I made a cut of dE > 150 keV, and got the timing plots below, which still seem to show a difference.

![tof_truth_de_hd](https://user-images.githubusercontent.com/1182058/41320940-c2c42f40-6e6f-11e8-9533-79dae3723a1f.png)
![tof_truth_de_hd4](https://user-images.githubusercontent.com/1182058/41320944-c696d686-6e6f-11e8-89d0-25dce8cf35d8.png)
![tof_truth_time_hd](https://user-images.githubusercontent.com/1182058/41320950-c7e9fca2-6e6f-11e8-8fa4-bca560a3a52c.png)
![tof_truth_time_hd4](https://user-images.githubusercontent.com/1182058/41320952-c951f900-6e6f-11e8-9ede-135e486a5278.png)

**Comment by rjones30** [comment]
Sean, this deltaE distribution comparison is much more tell-tale than the timing distribution. I suspect that the treatment of attenuation and time delay in the light propagation down the bars might be different. Let me have a look at this. -Richard

**Comment by sdobbs** [comment]
Richard, I noticed that in the code starting around https://github.com/JeffersonLab/HDGeant4/blob/1420b57f4601ad639e148523a3a4f89d0050942e/src/GlueXSensitiveDetectorFTOF.cc#L200
where the attenuation corrections are applied, from our discussion today I gathered that the natural units of Geant4 distances are mm, while constants like ATTENUATION_LENGTH are set to be in cm.  Does Geant4 do the unit conversions between these properly, or is this something we don't have to worry about?

**Comment by rjones30** [comment]
I have had a closer look at this, and from what I see there is a good agreement between what hdgeant and hdgeant4 are producing for the energy deposition and timing in the TOF. The following plots were generated directly from the hddm output from hdgeant[4], using the following python code.

import hddm_s
from ROOT import *
MeV = 1e3
def Ehist(name, hfile):
   h = TH1D(name, "", 200, 0, 20.)
   h.GetXaxis().SetTitle("dE of hit in tof (MeV)")
   h.GetYaxis().SetTitle("hits")
   for rec in hddm_s.istream(hfile):
      for bar in rec.getFtofCounters():
         dEleft = 0
         dEright = 0
         for hit in bar.getFtofTruthHits():
            if hit.end == 0:
               dEleft += hit.dE
            else:
               dEright += hit.dE
         dEtot = dEleft + dEright
         h.Fill(dEtot*MeV)
   return h
hE5 = Ehist("hE5", "test5.hddm")
hE6 = Ehist("hE6", "test6.hddm")
hE6.SetLineColor(kRed)

![image](https://user-images.githubusercontent.com/7832920/43147156-6417617e-8f30-11e8-982c-4974598c09a0.png)

Adding a similar python function for the timing,

def thist(name, hfile):
   h = TH1D(name, "", 200, 20, 40)
   h.GetXaxis().SetTitle("${\Delta (t_{hit} - t_{bunch})} (ns)")
   h.GetYaxis().SetTitle("hits")
   h.GetYaxis().SetTitleOffset(1.4)
   for rec in hddm_s.istream(hfile):
      tvtx = rec.getVertices()[0].getOrigins()[0].t
      for bar in rec.getFtofCounters():
         tleft = 1e9
         tright = 1e9
         for hit in bar.getFtofTruthHits():
            if hit.end == 0:
               tleft = hit.t if hit.t < tleft else tleft
            else:
               tright = hit.t if hit.t < tright else tright
         tmean = (tleft + tright)/2
         if tmean < 1e3:
            h.Fill(tmean - tvtx)
   return h
ht5 = thist("ht5", "test5.hddm")
ht6 = thist("ht6", "test6.hddm")
ht6.SetLineColor(kRed)

![image](https://user-images.githubusercontent.com/7832920/43147225-8a73eff4-8f30-11e8-8941-756e8adf9c69.png)

**Comment by rjones30** [comment]
Sean, one additional thing. When you generated those bggen samples, were you using multiple threads in hdgeant4? If so, you should try pulling the latest updates to JeffersonLab/HDGeant4, rebuild and try again. I submitted a fix that resolves a thread-contention bug that affects a few detector subsystems, the FCAL and FTOF being prime examples.

**Comment by sdobbs** [comment]
Richard, Thanks for the note, I've just been running single threaded in
order to stay away from multi-threading bugs.  I figure that once we have
the major issues resolved, then would be a good time to run a
multithreading test.

**Comment by sdobbs** [comment]
Yes, this is on my list...

**Comment by rjones30** [comment]
Just reran my same plot generator on these same simulation files after smearing, and the plots are unchanged. If there is not something that has been fixed (that I don't know of) in the code since this study was first done, I would conclude that there is a problem somewhere in Jana. Is there a cutoff being applied on the max number of hits per bar being read in by JANA?

**Comment by rjones30** [comment]
Based on the above, I report this issue as resolved at the level of the simulation + smearing.

**Comment by sdobbs** [comment]
Richard, I'm just trying to reproduce your results before looking at the single-track events - do they come from the HDDM files linked to in the first post, or some other data files?

**Comment by rjones30** [comment]
Sean,

These are ones that I made myself. They are generated with full-target
spread (set primary vertex to 0) at polar angle 5 deg, all azimuthal
angles, 3 GeV pi+ particle gun. The line from control.in for this is below.
KINE 108 3.0 5. 180. 0. 0. 360.

-Richard Jones

**Comment by sdobbs** [comment]
OK, thanks, that makes sense.  If I look at single track simulations, I do see a similar result.  So I'll close this for now.  

I'll add the corresponding bggen results below.

[time.pdf](https://github.com/JeffersonLab/HDGeant4/files/2243582/time.pdf)
[de.pdf](https://github.com/JeffersonLab/HDGeant4/files/2243583/de.pdf)
