### ISSUE TITLE
HOWTO on vertexing in Monte Carlo event generators for GlueX

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/HDGeant4#55]
- should discuss the needed correlation between t and z of the interaction point
- should discuss how to treat the decays of long-lived particles

**Comment by rjones30** [comment]
Please have a look at this, and tell me if it does the job.
https://halldweb.jlab.org/wiki/index.php/Guide_to_Monte_Carlo_event_timing_and_detached_vertices_in_HDGeant/4

**Comment by markito3** [comment]
Looks good!
