### ISSUE TITLE
Photon energy scale

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/HDGeant4#67]
To follow up on the discussion of pi0/eta mass shifts in HDGeant4 relative to HDGeant, I talked to Richard at the Collaboration Meeting, and he agreed to generate some photon gun simulations to compare the simulated shower energies in the two software.

**Comment by mashephe** [comment]
Naively, this seems conflict with a check that I did about 2 months ago, but perhaps I made a mistake.  (Or else someone recalibrated the MC between then and now.)  

https://logbooks.jlab.org/entry/3621347

Matt

---------------------------------------------------------------------
Matthew Shepherd, Professor
Department of Physics, Indiana University, Swain West 265
727 East Third Street, Bloomington, IN 47405

Office Phone:  +1 812 856 5808

**Comment by rjones30** [comment]
Matt and all,

What I show here are straight line fits, and not sensitive to the nonlinear
correction. There are non-linear effects in these sim data as well. The
issue I was addressing here was the "energy scale", a discrepancy between
the calorimeter energy scales between hdgeant and hdgeant4. Here is a link
to the issue posted to github.
https://github.com/JeffersonLab/HDGeant4/issues/67

This is only the beginning of matching the calorimeter response in MC to
real data, but we need to begin by understanding any differences we see
between hdgeant and hdgeant4. Once this is ok, then we can start work on
modeling the nonlinear response in mcsmear.

-Richard Jones

**Comment by rjones30** [comment]
P.S. At the same time as we work on the nonlinear response in the FCAL, I
think we also need to work on the theta-dependence. Because the fcal
real-data calibration uses pi0's, its position dependence will be different
from MC. This effect appears to be of the same order of magnitude as the
non-linear discrepancy shown by Matt in the above-referenced logbook entry.
In fact, to some extent they may feed into each other in simulated physics
events, due to the strong angle-energy correlation in fcal showers. The two
are clearly separated in a study like the one I report here, where there is
no energy-angle correlation in the generator.
-rtj

**Comment by markdalton** [comment]
Richard, I noticed that in the BCAL you throw events with energy more than 500 MeV but sometimes the thrown value that is plotted is less than this.  This occurs hdgeant but not hdgeant4.  Can you explain this?
Mark

**Comment by eltonssmith** [comment]
Hi Richard,
Thanks for following up on issues of energy reconstruction in both 
hdgeant and hdgeant4. We need to check this systematically. It would be 
good if you could present this work at our next Cal Working group 
meeting (Thu Jan 10). Also, could you post your slides to the portal (or 
the log book)? The google drive location is convenient in the short 
term, but gets lost over time. For the BCAL, in particular, we need to 
understand the origin of the offset that you see between generated and 
reconstructed energies.

Cheers, Elton.

Elton Smith
Jefferson Lab MS 12H3
12000 Jefferson Ave STE 4
Newport News, VA 23606
(757)269-7625
(757)269-6331 fax

**Comment by rjones30** [comment]
Mark,

Yes, this is a idiosyncrasy of hdgeant, where if a photon undergoes a
nuclear collision and generates a pi0 before entrance to the calorimeter,
and one of the pi0 decay photons enters the expected region of the
calorimeter then that photon and that shower appears in the output as the
generated/reconstructed pair. There are only 43 of these in the sample, out
of 100,000 so I don't think their presence is affecting the results in any
substantial way. In the non-linear study, I excluded most of those 43
points from the fit by a generated photon energy cut of 0.5 GeV.

-Richard Jones

**Comment by rjones30** [comment]
Hello Elton,

Good suggestion, I have now posted these slides in pdf format to the portal
as https://halldweb.jlab.org/doc-private/DocDB/ShowDocument?docid=3852

Please put me on the agenda to present this at the next calorimetry working
group meeting.

-Richard Jones

**Comment by sdobbs** [comment]
Hi Richard,

Since I brought this up in the first place, I should take a fresh look at the simulations I was running.  Just to make sure I'm on the same page, is the comparison you showed just on the output of hdgeant[4], or is it post-mcsmear & reconstruction?

---Sean

**Comment by rjones30** [comment]
Hello Sean,

This comparison is post-mcsmear, post-reconstruction. I am getting the
reconstructed shower energy from the REST file.

-Richard Jones
