### ISSUE TITLE
geant3 crash

### ISSUE THREAD

**Issue by zihlmann** [JeffersonLab/HDGeant4#68]
with my generator based on gen_amp geant3 crashes randomly on a generated event
when using the latest geometry from github. It does not crash if I use the geometry version 3.12
The crash happens with a ZFATAL error.

**Comment by rjones30** [comment]
Hello Beni,

Can you create a tarball with all of the necessary ingredients inside to
reproduce the crash?

-Richard J.

**Comment by zihlmann** [comment]
Hi Richard,
attached is the tar file containing the config file for the generator 
the config file for the mcwrapper
and the xml of my environment on the ifarm. this last one has now the line
  /><package name="hdds" version="3.12"
which makes it work
previously it had the line
  /><package name="hdds" home="/work/halld2/home/zihlmann/HallD/hdds"
which caused the crash usually in the first 10k events. Note that my private
version of the hdds directory contains the latest from github.

cheers,
Beni

**Comment by T-Britton** [comment]
To add to this:

I could successfully run Beni's generator with MCwrapper and my environment.  Looking over the xml file we determined that his "master" version of HDDS was to blame.  When he went back to 3.12 it runs successfully.  I am currently in the process of running his configuration with master HDDS to see if I can reproduce things.

**Comment by T-Britton** [comment]
I just cloned master HDDS and rebuilt HDDS, halld_recon, halld_sim in that order.  Fresh terminal to ensure I have a completely new environment. And I do not reproduce the crash.  My hypothesis is either the build order was incorrect, or a package was not fully cleaned which lead to an incompatibility with HDDS.

**Comment by zihlmann** [comment]
still get geant3 crash even after deleting hdds and halld_sim completely and build it from scratch.
the error is always in hdgeant with !ZFATAL :-(

**Comment by markito3** [comment]
Closing for now, Beni will work on it privately.
